language: node_js
node_js:
  - '8'
before_install: |
  set -e
  export PATH="./$HOME/node_modules/.bin:$PATH"
  npm install -g @alrra/travis-scripts
  date
install: |
  set -e
  date
  npm install -g lerna@^3.15.0
  lerna bootstrap 2>&1
  date
script: lerna run test 2>&1
dist: trusty
