#!/usr/bin/env node
// PROTOTYPE of codegen template-engine (or Concerto's TypeScript target)
// would provide: a runtime factory per concrete model type
// (runtime/logic.ts's `conceptType` / `identifiedType`), so logic never
// writes a `$class` by hand.
//
//   node scripts/generate-types.js <generated dir> <model dir>...
//
// Loads every .cto file in the model directories and writes
// <generated dir>/types.ts, covering each namespace Concerto's codegen
// already wrote a <namespace>.ts for in that directory. Run after
// `concerto compile`.
'use strict';

const fs = require('fs');
const path = require('path');
const { ModelManager } = require('@accordproject/concerto-core');

const [outDir, ...modelDirs] = process.argv.slice(2);
if (!outDir || modelDirs.length === 0) {
    console.error('Usage: generate-types.js <generated dir> <model dir>...');
    process.exit(1);
}

const models = new ModelManager();
for (const dir of modelDirs) {
    for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.cto')).sort()) {
        models.addCTOModel(fs.readFileSync(path.join(dir, file), 'utf8'), file, true);
    }
}
models.validateModelFiles();

const generated = new Set(fs.readdirSync(outDir).filter(f => f.endsWith('.ts')).map(f => f.slice(0, -3)));
const runtime = path.relative(outDir, path.join(__dirname, '..', 'runtime', 'logic')).split(path.sep).join('/');

const imports = [];
const factories = [];
const names = new Map();
for (const modelFile of models.getModelFiles().filter(m => generated.has(m.getNamespace()))) {
    const namespace = modelFile.getNamespace();
    const declarations = modelFile.getAllDeclarations()
        .filter(d => d.isClassDeclaration?.() && !d.isEnum?.() && !d.isAbstract())
        .sort((a, b) => a.getName().localeCompare(b.getName()));
    if (declarations.length === 0) {
        continue;
    }
    imports.push(`import { ${declarations.map(d => `I${d.getName()}`).join(', ')} } from './${namespace}';`);
    for (const d of declarations) {
        const name = d.getName();
        if (names.has(name)) {
            throw new Error(`${d.getFullyQualifiedName()} and ${names.get(name)} have the same short name.`);
        }
        names.set(name, d.getFullyQualifiedName());
        const id = d.isIdentified() && !d.isSystemIdentified() ? d.getIdentifierFieldName() : undefined;
        factories.push(id
            ? `export const ${name} = identifiedType<I${name}>()('${d.getFullyQualifiedName()}', '${id}');`
            : `export const ${name} = conceptType<I${name}>()('${d.getFullyQualifiedName()}');`);
    }
}

fs.writeFileSync(path.join(outDir, 'types.ts'), [
    '// Generated by scripts/generate-types.js from the models: one factory per',
    '// concrete type, so logic never writes a $class by hand. Do not edit.',
    `import { conceptType, identifiedType } from '${runtime}';`,
    ...imports,
    '',
    ...factories,
    '',
].join('\n'));
