name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Unit Tests
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm test
